journey
    title Software Developer User Journey
    section Develop Software
        Open IDE: 5: Me
        Select new feature: 5: Me
        Write code: 5: Me
        Test code: 5: Me
        Commit code 5: Me
        Deploy code: 5: Me
    section Publish Score
        Generate SCI score: 1: Me
        Fill in benchmark information: 1: Me
        Publish score: 1: Me